### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by BashoOps**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by BashoOps** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
Code reviews from: @davidpuddy1,@bobsmith1.
Merging and closing this PR.
Build Status:

#### merge

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:13:11.686496000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:13:13.933081000 -07:00
:result: :ok
:message: Merge Success

```

#### build

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:13:13.933123000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:13:13.941232000 -07:00
:result: :ok
:command: cd /tmp/thumbs/davidx_prtester_169 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/davidx_prtester_169 && make build
- |
  BUILD OK
- 0

```

#### test

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:13:13.941341000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:13:13.948985000 -07:00
:result: :ok
:command: cd /tmp/thumbs/davidx_prtester_169 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/davidx_prtester_169 && make test
- |
  TEST OK
- 0

```

**Pull request closed without merging**
