### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
Code reviews from: davidpuddy1,bobsmith1
Merging and Closing this PR.

```
{"steps":{"merge":{"started_at":"2016-08-05T11:56:50-07:00","ended_at":"2016-08-05T11:56:52-07:00","result":"ok","message":"Merge Success"},"build":{"started_at":"2016-08-05T11:56:52-07:00","ended_at":"2016-08-05T11:56:52-07:00","result":"ok","command":"cd /tmp/thumbs/davidx_prtester_66 && make build","output":"BUILD OK\n","exit_code":0,"message":["OK","cd /tmp/thumbs/davidx_prtester_66 && make build","BUILD OK\n",0]},"test":{"started_at":"2016-08-05T11:56:52-07:00","ended_at":"2016-08-05T11:56:52-07:00","result":"ok","command":"cd /tmp/thumbs/davidx_prtester_66 && make test","output":"TEST OK\n","exit_code":0,"message":["OK","cd /tmp/thumbs/davidx_prtester_66 && make test","TEST OK\n",0]}}}
```

**Pull request merged**
