### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
``````
      Looks good! :+1:
      Code reviews from: davidpuddy1,bobsmith1
      Merging and Closing this PR.
      ```
      ---
``````

:steps:
  :merge:
    :started_at: !ruby/object:DateTime 2016-08-05 11:24:24.033321000 -07:00
    :ended_at: !ruby/object:DateTime 2016-08-05 11:24:26.608373000 -07:00
    :result: :ok
    :message: Merge Success
  :build:
    :started_at: !ruby/object:DateTime 2016-08-05 11:24:26.608410000 -07:00
    :ended_at: !ruby/object:DateTime 2016-08-05 11:24:26.618686000 -07:00
    :result: :ok
    :command: cd /tmp/thumbs/davidx_prtester_42 && make build
    :output: |
      BUILD OK
    :exit_code: 0
    :message:
    - OK
    - cd /tmp/thumbs/davidx_prtester_42 && make build
    - |
      BUILD OK
    - 0
  :test:
    :started_at: !ruby/object:DateTime 2016-08-05 11:24:26.618810000 -07:00
    :ended_at: !ruby/object:DateTime 2016-08-05 11:24:26.627489000 -07:00
    :result: :ok
    :command: cd /tmp/thumbs/davidx_prtester_42 && make test
    :output: |
      TEST OK
    :exit_code: 0
    :message:
    - OK
    - cd /tmp/thumbs/davidx_prtester_42 && make test
    - |
      TEST OK
    - 0

``````
      ```
``````

**Pull request merged**
