### PR TITLE
creating for test PR

### PR DESCRIPTION
**Pull request by bobsmith1**
hi how bout these ?

### CODE REVIEW

**Comment by davidx** [comment]
test

**Comment by davidx** [comment]
hi

**Comment by bobsmith1** [comment]
what ?

**Comment by davidx** [comment]
<p>Build Status: Looks like there's an issue with build step merge !  :cloud: </p>

<details>
 <summary>

:no_entry: MERGE   ERROR </summary>



 <p>

> Started at: 2016-09-01 18:05
> Duration:  seconds.
> Result:  ERROR
> Message: Merge test failed
> Exit Code:  ERROR
> <a href="https://gist.github.com/791330b8613acf48c383ae067c15c0f6">[GIST]</a>
> </p>

```



#<Git::GitExecuteError: git '--git-dir=/tmp/thumbs/davidx_prtester_196/.git' '--work-tree=/tmp/thumbs/davidx_prtester_196' merge '-m' 'merge' '6b5d5c9a03ea088152e2b66f9e6919b97f5fea42'  2>&1:Auto-merging testfile1
CONFLICT (content): Merge conflict in testfile1
Automatic merge failed; fix conflicts and then commit the result.>

```

---

</details>

**Comment by davidx** [comment]
Build not valid for merge.

**Comment by davidx** [comment]
hi

**Comment by davidx** [comment]
hi

**Comment by bobsmith1** [comment]
hi

**Comment by bobsmith1** [comment]
hoi

**Comment by bobsmith1** [comment]
hai

**Comment by davidx** [comment]
<p>Build Status: Looks like there's an issue with build step merge !  :cloud: </p>

<details>
 <summary>

:no_entry: MERGE   ERROR </summary>



 <p>

> Started at: 2016-09-01 18:22
> Duration:  seconds.
> Result:  ERROR
> Message: Merge test failed
> Exit Code:  ERROR
> <a href="https://gist.github.com/3ef2da8205d34a9d24e7b687fa89c763">[GIST]</a>
> </p>

```



#<Git::GitExecuteError: git '--git-dir=/tmp/thumbs/davidx_prtester_196/.git' '--work-tree=/tmp/thumbs/davidx_prtester_196' merge '-m' 'merge' '6b5d5c9a03ea088152e2b66f9e6919b97f5fea42'  2>&1:Auto-merging testfile1
CONFLICT (content): Merge conflict in testfile1
Automatic merge failed; fix conflicts and then commit the result.>

```

---

</details>

**Comment by davidx** [comment]
Build not valid for merge.

**Comment by bobsmith1** [comment]
yes

**Comment by bobsmith1** [comment]
hi

**Comment by bobsmith1** [comment]
hi

**Comment by davidx** [comment]
hi

**Comment by davidpuddy1** [comment]
hi

**Comment by davidpuddy1** [comment]
yo?

**Pull request closed without merging**
