### PR TITLE
Test variables

### PR DESCRIPTION
**Pull request by davidx**

### CODE REVIEW

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
test

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
thumbot retry

**Comment by davidx** [comment]
la la  la

**Comment by davidx** [comment]
la la  la

**Comment by davidx** [comment]
la la  la

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
testing lotta comments

**Comment by davidx** [comment]
+1

**Comment by davidx** [comment]
+1

**Comment by davidpuddy1** [comment]
thumbot retry

**Comment by davidpuddy1** [comment]
thumbot retry

**Comment by davidpuddy1** [comment]
thumbot retry

**Pull request merged**
