### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
2 Code reviews from: @davidpuddy1,@bobsmith1 %>
Merging and closing this PR.
Build Status:

#### [:merge, {:started_at=>#<DateTime: 2016-08-05T13:06:01-07:00 ((2457606j,72361s,734382000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T13:06:08-07:00 ((2457606j,72368s,235623000n),-25200s,2299161j)>, :result=>:ok, :message=>"Merge Success"}]

```
--- 
...

```

#### [:build, {:started_at=>#<DateTime: 2016-08-05T13:06:08-07:00 ((2457606j,72368s,235675000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T13:06:08-07:00 ((2457606j,72368s,244458000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_159 && make build", :output=>"BUILD OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_159 && make build", "BUILD OK\n", 0]}]

```
--- 
...

```

#### [:test, {:started_at=>#<DateTime: 2016-08-05T13:06:08-07:00 ((2457606j,72368s,244641000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T13:06:08-07:00 ((2457606j,72368s,252684000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_159 && make test", :output=>"TEST OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_159 && make test", "TEST OK\n", 0]}]

```
--- 
...

```

**Comment by BashoOps** [comment]
Merge successfull!

**Pull request merged**
