### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
Code reviews from: davidpuddy1,bobsmith1
Merging and Closing this PR.

```
{:steps=>{:merge=>{:started_at=>#<DateTime: 2016-08-05T11:46:57-07:00 ((2457606j,67617s,315629000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:47:00-07:00 ((2457606j,67620s,862278000n),-25200s,2299161j)>, :result=>:ok, :message=>"Merge Success"}, :build=>{:started_at=>#<DateTime: 2016-08-05T11:47:00-07:00 ((2457606j,67620s,862321000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:47:00-07:00 ((2457606j,67620s,871049000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_60 && make build", :output=>"BUILD OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_60 && make build", "BUILD OK\n", 0]}, :test=>{:started_at=>#<DateTime: 2016-08-05T11:47:00-07:00 ((2457606j,67620s,871185000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:47:00-07:00 ((2457606j,67620s,879795000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_60 && make test", :output=>"TEST OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_60 && make test", "TEST OK\n", 0]}}}
```

**Pull request merged**
