### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
``````
      Looks good! :+1:
      Code reviews from: davidpuddy1,bobsmith1
      Merging and Closing this PR.
      ```
      {:steps=>{:merge=>{:started_at=>#<DateTime: 2016-08-05T11:44:35-07:00 ((2457606j,67475s,222964000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:44:37-07:00 ((2457606j,67477s,824769000n),-25200s,2299161j)>, :result=>:ok, :message=>"Merge Success"}, :build=>{:started_at=>#<DateTime: 2016-08-05T11:44:37-07:00 ((2457606j,67477s,824818000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:44:37-07:00 ((2457606j,67477s,833433000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_56 && make build", :output=>"BUILD OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_56 && make build", "BUILD OK\n", 0]}, :test=>{:started_at=>#<DateTime: 2016-08-05T11:44:37-07:00 ((2457606j,67477s,833582000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:44:37-07:00 ((2457606j,67477s,841717000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_56 && make test", :output=>"TEST OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_56 && make test", "TEST OK\n", 0]}}}
      ```
``````

**Pull request merged**
