### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
Looks good! :+1:
2 Code reviews from: @davidpuddy1,@bobsmith1 %>
Merging and closing this PR.
Build Status:

#### [:merge, {:started_at=>#<DateTime: 2016-08-05T13:07:06-07:00 ((2457606j,72426s,145522000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T13:07:08-07:00 ((2457606j,72428s,391475000n),-25200s,2299161j)>, :result=>:ok, :message=>"Merge Success"}]

```
--- 
...

```

#### [:build, {:started_at=>#<DateTime: 2016-08-05T13:07:08-07:00 ((2457606j,72428s,391515000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T13:07:08-07:00 ((2457606j,72428s,399649000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_162 && make build", :output=>"BUILD OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_162 && make build", "BUILD OK\n", 0]}]

```
--- 
...

```

#### [:test, {:started_at=>#<DateTime: 2016-08-05T13:07:08-07:00 ((2457606j,72428s,399817000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T13:07:08-07:00 ((2457606j,72428s,408040000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_162 && make test", :output=>"TEST OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_162 && make test", "TEST OK\n", 0]}]

```
--- 
...

```

**Comment by BashoOps** [comment]
Merge successfull!

**Pull request merged**
