### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
``````
      Looks good! :+1:
      Code reviews from: davidpuddy1,bobsmith1
      Merging and Closing this PR.
      ```
      {:steps=>{:merge=>{:started_at=>#<DateTime: 2016-08-05T11:43:54-07:00 ((2457606j,67434s,838752000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:43:56-07:00 ((2457606j,67436s,635535000n),-25200s,2299161j)>, :result=>:ok, :message=>"Merge Success"}, :build=>{:started_at=>#<DateTime: 2016-08-05T11:43:56-07:00 ((2457606j,67436s,635572000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:43:56-07:00 ((2457606j,67436s,644085000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_54 && make build", :output=>"BUILD OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_54 && make build", "BUILD OK\n", 0]}, :test=>{:started_at=>#<DateTime: 2016-08-05T11:43:56-07:00 ((2457606j,67436s,644226000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:43:56-07:00 ((2457606j,67436s,652800000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_54 && make test", :output=>"TEST OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_54 && make test", "TEST OK\n", 0]}}}
      ```
``````

**Pull request merged**
