### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by BashoOps** [comment]
``````
      Looks good! :+1:
      Code reviews from: davidpuddy1,bobsmith1
      Merging and Closing this PR.
      ```
      {:steps=>{:merge=>{:started_at=>#<DateTime: 2016-08-05T11:46:23-07:00 ((2457606j,67583s,852611000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:46:25-07:00 ((2457606j,67585s,614412000n),-25200s,2299161j)>, :result=>:ok, :message=>"Merge Success"}, :build=>{:started_at=>#<DateTime: 2016-08-05T11:46:25-07:00 ((2457606j,67585s,614466000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:46:25-07:00 ((2457606j,67585s,622978000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_59 && make build", :output=>"BUILD OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_59 && make build", "BUILD OK\n", 0]}, :test=>{:started_at=>#<DateTime: 2016-08-05T11:46:25-07:00 ((2457606j,67585s,623147000n),-25200s,2299161j)>, :ended_at=>#<DateTime: 2016-08-05T11:46:25-07:00 ((2457606j,67585s,631773000n),-25200s,2299161j)>, :result=>:ok, :command=>"cd /tmp/thumbs/davidx_prtester_59 && make test", :output=>"TEST OK\n", :exit_code=>0, :message=>["OK", "cd /tmp/thumbs/davidx_prtester_59 && make test", "TEST OK\n", 0]}}}
      ```
``````

**Pull request merged**
