### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
<p>Thanks @davidx!</p>

<p>Build Status: *Looks good!*  :+1:</p>

<details>
 <summary>

:white_check_mark: MERGE   OK <a href="https://gist.github.com/2cbe11482bc6158610ae12d9e3393846">[Gist]</a> </summary>



 <p>

> Started at: 2016-08-23 09:54
> Duration: 1 seconds.
> Result:  OK
> Message: Merge Success: 55c0f7e4578cece9ccfaf9b3d26ee2c353b771dc onto target branch: master
> Exit Code:  OK

</p>

```



Updating 420b041..55c0f7e
Fast-forward (no commit created; -m option ignored)
 testfile1 | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

```

---

</details>

<details>
 <summary>

:white_check_mark: MAKE   OK <a href="https://gist.github.com/921bf817d4faf85a8c5123dd88b257f7">[Gist]</a> </summary>



 <p>

> Started at: 2016-08-23 09:54
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

</p>

```

cd /tmp/thumbs/davidx_prtester_193 && make 2>&1

OK


```

---

</details>

<details>
 <summary>

:white_check_mark: MAKE_BUILD   OK <a href="https://gist.github.com/8b563c7b2def66f88b911901f56a2b39">[Gist]</a> </summary>



 <p>

> Started at: 2016-08-23 09:54
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

</p>

```

cd /tmp/thumbs/davidx_prtester_193 && make build 2>&1

BUILD OK


```

---

</details>

<details>
 <summary>

:white_check_mark: MAKE_TEST   OK <a href="https://gist.github.com/394a7d32e750349d45c8a89139907a5f">[Gist]</a> </summary>



 <p>

> Started at: 2016-08-23 09:54
> Duration: 0 seconds.
> Result:  OK
> Message: OK
> Exit Code:  0

</p>

```

cd /tmp/thumbs/davidx_prtester_193 && make test 2>&1

TEST OK


```

---

</details>

**Comment by davidx** [comment]
Hey Guys, check out my PR, think its pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by davidx** [comment]
Looks good +1

**Comment by davidx** [comment]
tr

**Comment by davidx** [comment]
hello

**Comment by davidx** [comment]
hey

**Comment by davidx** [comment]
yo

**Comment by davidx** [comment]
interesting

**Pull request merged**
