### PR TITLE
Testing PR

### PR DESCRIPTION
**Pull request by davidx**
Thumbs Git Robot: This pr has been created for testing purposes

### CODE REVIEW

**Comment by davidx** [comment]
I think this is pretty sweet!

**Comment by davidpuddy1** [comment]
YAAAAAAAASSSS +1

**Comment by bobsmith1** [comment]
Looks good +1

**Comment by davidx** [comment]
Looks good! :+1:
Code reviews from: @davidpuddy1,@bobsmith1.
Merging and closing this PR.
Build Status:

#### merge

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:32:13.043664000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:32:17.470115000 -07:00
:result: :ok
:message: Merge Success

```

#### build

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:32:17.470156000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:32:17.478100000 -07:00
:result: :ok
:command: cd /tmp/thumbs/davidx_prtester_180 && make build
:output: |
  BUILD OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/davidx_prtester_180 && make build
- |
  BUILD OK
- 0

```

#### test

```
---
:started_at: !ruby/object:DateTime 2016-08-05 13:32:17.478240000 -07:00
:ended_at: !ruby/object:DateTime 2016-08-05 13:32:17.486143000 -07:00
:result: :ok
:command: cd /tmp/thumbs/davidx_prtester_180 && make test
:output: |
  TEST OK
:exit_code: 0
:message:
- OK
- cd /tmp/thumbs/davidx_prtester_180 && make test
- |
  TEST OK
- 0

```

**Comment by davidx** [comment]
Merge successfull!

**Pull request merged**
